# Generated by Django 4.2 on 2023-05-28 16:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_name', models.CharField(max_length=100)),
                ('order_quantity', models.IntegerField(default=1)),
                ('customer_email', models.EmailField(blank=True, max_length=300, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_recieved_date', models.DateField(blank=True, null=True)),
                ('order_due_date', models.DateField(blank=True, null=True)),
                ('order_priorty', models.IntegerField(blank=True, default=0, null=True)),
                ('order_status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('CUTTING', 'Cutting'), ('STICHING', 'Stiching'), ('DELIVERED', 'Delivered')], default='RECEIVED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mesurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('customer_email', models.EmailField(max_length=300, null=True)),
                ('customer_phone', models.IntegerField()),
                ('front_length', models.CharField(blank=True, max_length=20, null=True)),
                ('shoulder', models.CharField(blank=True, max_length=20, null=True)),
                ('sleeves', models.CharField(blank=True, max_length=20, null=True)),
                ('chest', models.CharField(blank=True, max_length=20, null=True)),
                ('waist', models.CharField(blank=True, max_length=20, null=True)),
                ('hip', models.CharField(blank=True, max_length=20, null=True)),
                ('crossfront', models.CharField(blank=True, max_length=20, null=True)),
                ('crossback', models.CharField(blank=True, max_length=20, null=True)),
                ('sherwani_vest', models.CharField(blank=True, max_length=50, null=True)),
                ('slits', models.CharField(blank=True, choices=[(None, 'None'), ('Side', 'Side'), ('Center', 'Center')], max_length=10, null=True)),
                ('Blazer_Jacket_Additional_Information', models.TextField(blank=True, max_length=2000, null=True)),
                ('Blazer_sample_cloth_image', models.ImageField(blank=True, null=True, upload_to='sample_images/blazers')),
                ('kurta_front_length', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_shoulder', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_sleeves', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_chest', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_waist', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_hip', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_sleeves_opening', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_biceps', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_Cut_Choices', models.CharField(blank=True, choices=[("Slim 4'", "Slim 4'"), ("M FIT 5'", "M FIT 5'"), ("Loose 6'", "Loose 6'")], max_length=20, null=True)),
                ('kurta_Style_Choices', models.CharField(blank=True, choices=[('Square Slit', 'Square Slit'), ('Open Shirt', "M FIT 5'")], max_length=20, null=True)),
                ('kurta_Neck_Choices', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Short', 'Short'), ('Long', 'Long')], max_length=20, null=True)),
                ('kurta_Collor_Choices', models.FloatField(blank=True, choices=[(2, 2), (2.5, 2.5), (2.75, 2.75)], max_length=20, null=True)),
                ('Kurta_Shirt_Additional_Information', models.TextField(blank=True, max_length=2000, null=True)),
                ('Kurta_sample_cloth_image', models.ImageField(blank=True, null=True, upload_to='sample_images/kurta')),
                ('Tourser_length', models.CharField(blank=True, max_length=20, null=True)),
                ('Tourser_inseam', models.CharField(blank=True, max_length=20, null=True)),
                ('Tourser_bottom', models.CharField(blank=True, max_length=20, null=True)),
                ('Tourser_knee', models.CharField(blank=True, max_length=20, null=True)),
                ('Tourser_thigh', models.CharField(blank=True, max_length=20, null=True)),
                ('Tourser_waist', models.CharField(blank=True, max_length=20, null=True)),
                ('Tourser_hips', models.CharField(blank=True, max_length=20, null=True)),
                ('Tourser_rounding', models.CharField(blank=True, max_length=20, null=True)),
                ('Rise_Choices', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True)),
                ('front_Down', models.CharField(blank=True, max_length=50, null=True)),
                ('Pleat_Choices', models.CharField(blank=True, choices=[('Flat Front', 'Flat Front'), ('1 Pleat', '1 Pleat'), ('2 Pleat', '2 Pleat')], max_length=20, null=True)),
                ('Belt_Choices', models.CharField(blank=True, choices=[('Cut Belt', 'Cut Belt'), ('Ext. Belt', 'Ext. Belt')], max_length=20, null=True)),
                ('Pocket_Choices', models.CharField(blank=True, choices=[('Cross', 'Cross'), ('Side', 'Side')], max_length=20, null=True)),
                ('Watch_Pocket_Choices', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('Watch_Pocket_Number', models.IntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True)),
                ('Mobile_Pockets', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('pocketSize', models.CharField(blank=True, max_length=50, null=True)),
                ('Trouser_Additional_Information', models.TextField(blank=True, max_length=2000, null=True)),
                ('Trouser_sample_cloth_image', models.ImageField(blank=True, null=True, upload_to='sample_images/trouser')),
                ('blazer_image', models.ImageField(blank=True, default='/form/blazer-jacket.bmp', null=True, upload_to='blazer_images')),
                ('kurta_image', models.ImageField(blank=True, default='/form/shirt-kurta.bmp', null=True, upload_to='kurta_images')),
                ('trouser_image', models.ImageField(blank=True, default='/form/trouser.bmp', null=True, upload_to='trouser_images')),
                ('order', models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
