# Generated by Django 4.2 on 2023-05-16 10:45

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlazerMesurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.IntegerField(blank=True, null=True)),
                ('front_length', models.CharField(blank=True, max_length=20, null=True)),
                ('shoulder', models.CharField(blank=True, max_length=20, null=True)),
                ('sleeves', models.CharField(blank=True, max_length=20, null=True)),
                ('chest', models.CharField(blank=True, max_length=20, null=True)),
                ('waist', models.CharField(blank=True, max_length=20, null=True)),
                ('hip', models.CharField(blank=True, max_length=20, null=True)),
                ('crossfront', models.CharField(blank=True, max_length=20, null=True)),
                ('crossback', models.CharField(blank=True, max_length=20, null=True)),
                ('sherwani_vest', models.CharField(blank=True, max_length=50, null=True)),
                ('slits', models.CharField(blank=True, choices=[(None, 'None'), ('Side', 'Side'), ('Center', 'Center')], max_length=10, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='KurtaMesurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.IntegerField(blank=True, null=True)),
                ('front_length', models.CharField(blank=True, max_length=20, null=True)),
                ('shoulder', models.CharField(blank=True, max_length=20, null=True)),
                ('sleeves', models.CharField(blank=True, max_length=20, null=True)),
                ('chest', models.CharField(blank=True, max_length=20, null=True)),
                ('waist', models.CharField(blank=True, max_length=20, null=True)),
                ('hip', models.CharField(blank=True, max_length=20, null=True)),
                ('sleeves_opening', models.CharField(blank=True, max_length=20, null=True)),
                ('biceps', models.CharField(blank=True, max_length=20, null=True)),
                ('Cut_Choices', models.CharField(blank=True, choices=[("Slim 4'", "Slim 4'"), ("M FIT 5'", "M FIT 5'"), ("Loose 6'", "Loose 6'")], max_length=20, null=True)),
                ('Style_Choices', models.CharField(blank=True, choices=[('Square Slit', 'Square Slit'), ('Open Shirt', "M FIT 5'")], max_length=20, null=True)),
                ('Neck_Choices', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Short', 'Short'), ('Long', 'Long')], max_length=20, null=True)),
                ('Collor_Choices', models.FloatField(blank=True, choices=[(2, 2), (2.5, 2.5), (2.75, 2.75)], max_length=20, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_name', models.CharField(max_length=100)),
                ('order_status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='RECEIVED', max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=300, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrouserMesurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.IntegerField(blank=True, null=True)),
                ('length', models.CharField(blank=True, max_length=20, null=True)),
                ('inseam', models.CharField(blank=True, max_length=20, null=True)),
                ('bottom', models.CharField(blank=True, max_length=20, null=True)),
                ('knee', models.CharField(blank=True, max_length=20, null=True)),
                ('thigh', models.CharField(blank=True, max_length=20, null=True)),
                ('waist', models.CharField(blank=True, max_length=20, null=True)),
                ('hips', models.CharField(blank=True, max_length=20, null=True)),
                ('rounding', models.CharField(blank=True, max_length=20, null=True)),
                ('Rise_Choices', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True)),
                ('front_Down', models.CharField(blank=True, max_length=50, null=True)),
                ('Pleat_Choices', models.CharField(blank=True, choices=[('Flat Front', 'Flat Front'), ('1 Pleat', '1 Pleat'), ('2 Pleat', '2 Pleat')], max_length=20, null=True)),
                ('Belt_Choices', models.CharField(blank=True, choices=[('Cut Belt', 'Cut Belt'), ('Ext. Belt', 'Ext. Belt')], max_length=20, null=True)),
                ('Pocket_Choices', models.CharField(blank=True, choices=[('Cross', 'Cross'), ('Side', 'Side')], max_length=20, null=True)),
                ('Watch_Pocket_Choices', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('Watch_Pocket_Number', models.IntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True)),
                ('Mobile_Pockets', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('pocketSize', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
