# Generated by Django 4.2 on 2023-05-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blazermesurement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kurtamesurement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trousermesurement',
            name='created_at',
        ),
    ]
