# Generated by Django 4.2 on 2023-05-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_blazermesurement_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_length', models.CharField(blank=True, max_length=20, null=True)),
                ('shoulder', models.CharField(blank=True, max_length=20, null=True)),
                ('sleeves', models.CharField(blank=True, max_length=20, null=True)),
                ('chest', models.CharField(blank=True, max_length=20, null=True)),
                ('hip', models.CharField(blank=True, max_length=20, null=True)),
                ('crossfront', models.CharField(blank=True, max_length=20, null=True)),
                ('crossback', models.CharField(blank=True, max_length=20, null=True)),
                ('sherwani_vest', models.CharField(blank=True, max_length=50, null=True)),
                ('slits', models.CharField(blank=True, choices=[(None, 'None'), ('Side', 'Side'), ('Center', 'Center')], max_length=10, null=True)),
                ('kurta_front_length', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_shoulder', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_sleeves', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_chest', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_waist', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_hip', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_sleeves_opening', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_biceps', models.CharField(blank=True, max_length=20, null=True)),
                ('kurta_Cut_Choices', models.CharField(blank=True, choices=[("Slim 4'", "Slim 4'"), ("M FIT 5'", "M FIT 5'"), ("Loose 6'", "Loose 6'")], max_length=20, null=True)),
                ('kurta_Style_Choices', models.CharField(blank=True, choices=[('Square Slit', 'Square Slit'), ('Open Shirt', "M FIT 5'")], max_length=20, null=True)),
                ('kurta_Neck_Choices', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Short', 'Short'), ('Long', 'Long')], max_length=20, null=True)),
                ('kurta_Collor_Choices', models.FloatField(blank=True, choices=[(2, 2), (2.5, 2.5), (2.75, 2.75)], max_length=20, null=True)),
                ('Tourser_length', models.CharField(blank=True, max_length=20, null=True)),
                ('Tourser_inseam', models.CharField(blank=True, max_length=20, null=True)),
                ('Tourser_bottom', models.CharField(blank=True, max_length=20, null=True)),
                ('Tourser_knee', models.CharField(blank=True, max_length=20, null=True)),
                ('Tourser_thigh', models.CharField(blank=True, max_length=20, null=True)),
                ('Tourser_waist', models.CharField(blank=True, max_length=20, null=True)),
                ('Tourser_hips', models.CharField(blank=True, max_length=20, null=True)),
                ('Tourser_rounding', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.IntegerField(blank=True, null=True)),
                ('length', models.CharField(blank=True, max_length=20, null=True)),
                ('inseam', models.CharField(blank=True, max_length=20, null=True)),
                ('bottom', models.CharField(blank=True, max_length=20, null=True)),
                ('knee', models.CharField(blank=True, max_length=20, null=True)),
                ('thigh', models.CharField(blank=True, max_length=20, null=True)),
                ('waist', models.CharField(blank=True, max_length=20, null=True)),
                ('hips', models.CharField(blank=True, max_length=20, null=True)),
                ('rounding', models.CharField(blank=True, max_length=20, null=True)),
                ('Rise_Choices', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True)),
                ('front_Down', models.CharField(blank=True, max_length=50, null=True)),
                ('Pleat_Choices', models.CharField(blank=True, choices=[('Flat Front', 'Flat Front'), ('1 Pleat', '1 Pleat'), ('2 Pleat', '2 Pleat')], max_length=20, null=True)),
                ('Belt_Choices', models.CharField(blank=True, choices=[('Cut Belt', 'Cut Belt'), ('Ext. Belt', 'Ext. Belt')], max_length=20, null=True)),
                ('Pocket_Choices', models.CharField(blank=True, choices=[('Cross', 'Cross'), ('Side', 'Side')], max_length=20, null=True)),
                ('Watch_Pocket_Choices', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('Watch_Pocket_Number', models.IntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True)),
                ('Mobile_Pockets', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('pocketSize', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlazerMesurement',
        ),
        migrations.DeleteModel(
            name='KurtaMesurement',
        ),
        migrations.DeleteModel(
            name='TrouserMesurement',
        ),
    ]
