# Generated by Django 4.2 on 2023-05-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_mesurement_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesurement',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
