# Generated by Django 4.2 on 2023-05-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_mesurement_customer_name_order_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesurement',
            name='order',
        ),
    ]
