# Generated by Django 4.2 on 2023-05-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_mesurement_delete_blazermesurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesurement',
            name='Blazer_Jacket_Additional_Information',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='mesurement',
            name='Kurta_Shirt_Additional_Information',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='mesurement',
            name='Trouser_Additional_Information',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
