# Generated by Django 4.2 on 2023-05-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_mesurement_blazer_jacket_additional_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesurement',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
    ]
