# Generated by Django 4.2 on 2023-05-28 17:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_mesurement_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesurement',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mesurement',
            name='order',
            field=models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
