# Generated by Django 4.2 on 2023-05-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_mesurement_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesurement',
            name='bottom',
        ),
        migrations.RemoveField(
            model_name='mesurement',
            name='hips',
        ),
        migrations.RemoveField(
            model_name='mesurement',
            name='inseam',
        ),
        migrations.RemoveField(
            model_name='mesurement',
            name='knee',
        ),
        migrations.RemoveField(
            model_name='mesurement',
            name='length',
        ),
        migrations.RemoveField(
            model_name='mesurement',
            name='rounding',
        ),
        migrations.RemoveField(
            model_name='mesurement',
            name='thigh',
        ),
        migrations.AddField(
            model_name='mesurement',
            name='blazer_image',
            field=models.ImageField(blank=True, default='/form/blazer-jacket.bmp', null=True, upload_to='blazer_images'),
        ),
        migrations.AddField(
            model_name='mesurement',
            name='kurta_image',
            field=models.ImageField(blank=True, default='/form/shirt-kurta.bmp', null=True, upload_to='kurta_images'),
        ),
        migrations.AddField(
            model_name='mesurement',
            name='trouser_image',
            field=models.ImageField(blank=True, default='/form/trouser.bmp', null=True, upload_to='trouser_images'),
        ),
    ]
