# Generated by Django 4.2 on 2023-05-28 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_mesurement_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesurement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
