# Generated by Django 4.2 on 2023-06-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_mesurement_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_quantity',
        ),
        migrations.AddField(
            model_name='mesurement',
            name='order_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('PROCESSING', 'PROCESSING'), ('CUTTING STARTED', 'CUTTING STARTED'), ('STITCHING STARTED', 'STITCHING STARTED'), ('ORDER READY', 'ORDER READY'), ('QUALITY CHECK PASSED', 'QUALITY CHECKED PASSED'), ('QUALITY CHECK FAILED', 'QUALITY CHECKED FAILED'), ('DELIVERED', 'DELIVERED')], default='RECEIVED', max_length=200),
        ),
    ]
