# Generated by Django 4.2 on 2023-06-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_rename_order_quantity_mesurement_jacket_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_of_order_done',
            field=models.IntegerField(default=0),
        ),
    ]
