# Generated by Django 4.2 on 2023-06-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_number_of_order_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesurement',
            old_name='Tourser_bottom',
            new_name='Trouser_bottom',
        ),
        migrations.RenameField(
            model_name='mesurement',
            old_name='Tourser_hips',
            new_name='Trouser_hips',
        ),
        migrations.RenameField(
            model_name='mesurement',
            old_name='Tourser_inseam',
            new_name='Trouser_inseam',
        ),
        migrations.RenameField(
            model_name='mesurement',
            old_name='Tourser_knee',
            new_name='Trouser_knee',
        ),
        migrations.RenameField(
            model_name='mesurement',
            old_name='Tourser_length',
            new_name='Trouser_length',
        ),
        migrations.RenameField(
            model_name='mesurement',
            old_name='Tourser_rounding',
            new_name='Trouser_rounding',
        ),
        migrations.RenameField(
            model_name='mesurement',
            old_name='Tourser_thigh',
            new_name='Trouser_thigh',
        ),
        migrations.RenameField(
            model_name='mesurement',
            old_name='Tourser_waist',
            new_name='Trouser_waist',
        ),
    ]
