# Generated by Django 4.2 on 2023-06-07 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_rename_tourser_bottom_mesurement_trouser_bottom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesurement',
            name='id',
        ),
        migrations.AlterField(
            model_name='mesurement',
            name='order',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='measurement', serialize=False, to='order.order'),
        ),
    ]
